name: "Default user"
stages:
  initramfs:
  - files:
    - path: /etc/issue.d/99_passwd
      if: '[ -f /run/cos/live_mode ]'
      content: |
        System should auto install according to the parameters in the 98_elemental_install_from_iso.yaml
        
        If you have not configured it properly (i.e. wrong device) you can install the system with `elemental install --reboot DEVICE` manually

    ensure_entities:
    - path: /etc/shadow
      entity: |
        kind: "shadow"
        username: "root"
        password: "watson"
