name: build-iso

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage
      - name: Build iso
        run: |
          make build_all
      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: iso-image
          path: build/*.iso